### ISSUE TITLE
Add package to awesome-go

### ISSUE THREAD

**Issue by felipeweb** [Nhanderu/brdoc#1]
Need some changes see https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md

**Comment by Nhanderu** [comment]
I think that this projects has nothing to do with the awesome-go list. One reason for this is that it is not actively maintained (neither awesome 😂).

**Comment by felipeweb** [comment]
i will help you to maintain this package... the awesome-go list will make this package visible and your profile too. but if you don't want the packge on awesome-go you close the issue
