### ISSUE TITLE
Dúvida sobre validação do cep

### ISSUE THREAD

**Issue by renatosuero** [Nhanderu/brdoc#15]
Na validação de cep há um for para checar o range pelo estado [aqui](https://github.com/Nhanderu/brdoc/blob/856470c20b8437802d9db24778991efe375b41e5/cep.go#L28), como não há estados que estão no mesmo range faz sentido ter o for? 
Caso ainda seja válido mandar o cep + uf faz sentido rodar um for e não validar só o caso direto?

**Comment by Nhanderu** [comment]
Opa, desculpa a demora para te responder! Acho que eu entendi seu ponto. Ao invés de verificar todos os valores de `h` em todos os `ufs`, só procurar pela UF correta baseado no valor anterior, certo? Parece fazer sentido.

**Comment by Nhanderu** [comment]
Quer abrir uma PR para isso? Se não, eu posso ajustar mesmo, mas como a ideia é tua, é justo. haha

**Comment by renatosuero** [comment]
Desculpa minha demora agora :( não recebi notificação , claro farei isso entre hj e amanhã 😉

**Comment by renatosuero** [comment]
Semana complicada acabei esquecendo, acabei de mandar a PR com a alteração, removi o esquema de aceitar múltiplos estados e tbm movi as const uf para o começo do arquivo.

**Comment by Nhanderu** [comment]
Fala, amigo! Acabei deixando você sem resposta e peço mil desculpas por isso.
Dei uma olhada no seu PR e acho que volto atrás no que disse. Não sei se entendi seu ponto. Qual o benefício de remover a lista e validar apenas um valor?
Meu ponto de ter feito a lista é 1) pois eu realmente precisava validar se um CEP estava dentro de dois possíveis estados, e isso pouparia chamadas de regex e 2) se eu não quiser validar por estado algum, creio que fiquei visualmente mais limpo do que passar um `0`. Ainda sim, adoraria ouvir sua opinião sobre o assunto.
Obrigado pela contribuição!

**Comment by renatosuero** [comment]
Olá @Nhanderu eu não tinha pensando nessa parte de validar por uma região por ex. cep valido para sudeste. Sendo assim não faz sentido oq falei mesmo. Dessa forma fica muito melhor mesmo.
Acho que podemos fechar a issue e a pr , foi mal pelo seu tempo nessa :(

**Comment by Nhanderu** [comment]
Não se preocupa não! haha
Agradeço bastante pela sua ajuda, principalmente pela validação de CNS.
Abração, amigo!
