### ISSUE TITLE
Renavam Validator

### ISSUE THREAD

**Issue by leogregianin** [Nhanderu/brdoc#8]

**Comment by Nhanderu** [comment]
@leogregianin 
Abri novamente a issue porque, infelizmente, os testes da implementação atual não estão passando.
> `#1 Renavam validation of 17058862280 should return true: ✗`

**Comment by leogregianin** [comment]
@Nhanderu, reescrevi a função e adicionei mais testes :D Se puder revisar por favor.

**Comment by Nhanderu** [comment]
OK! Vou testar assim que possível. :)
