### ISSUE TITLE
CNH Validator

### ISSUE THREAD

**Issue by leogregianin** [Nhanderu/brdoc#9]
```Carteira Nacional de Habilitação```

**Comment by eminetto** [comment]
Eu encontrei esse algoritmo:
https://codigofonte.com.br/codigos/validacao-de-cnh
Alguém sabe se é correto esse cálculo? Se alguém tiver outra fonte e puder compartilhar, seria útil pra implementar mais rapidamente ;)

**Comment by leogregianin** [comment]
Pode ajudar sim.
Essa função também pode ajudar: https://github.com/frones/ACBr/blob/master/Fontes/ACBrDiversos/ACBrValidador.pas#L1950
